import type { Locale } from '@/content/types';

/**
 * The contact-intake data contract.
 *
 * One schema, shared by the validator, the store, the mailer and the tests, so
 * a field cannot mean one thing in the form and another in the database. The
 * server is authoritative for everything the client must not be trusted with —
 * `submittedAt`, `status`, `referenceId`, notification state — none of which
 * appear in `ContactInput`.
 */

/** Exactly the fields a submission is allowed to carry. Anything else is rejected. */
export interface ContactInput {
  locale: Locale;
  fullName: string;
  companyName: string;
  city: string;
  phoneOrEmail: string;
  activityType: string;
  interestedProduct: string;
  timeframe: string;
  preferredContactMethod: string;
  /** Optional free text. */
  challenge: string;
  /** Inquiry-response consent. Must be true, or the submission is refused. */
  consent: boolean;
  /** Marketing consent. Separate, opt-in, defaults false — never merged with `consent`. */
  marketingConsent: boolean;
  /** The page the form was submitted from. Coerced to a same-site value server-side. */
  pageUrl: string;
}

/** The lifecycle status of a lead. Client input can never set this. */
export type LeadStatus = 'NEW' | 'CONTACTED' | 'QUALIFIED' | 'ARCHIVED';

/** The delivery state of the notification email, tracked apart from the lead itself. */
export type NotificationStatus = 'PENDING' | 'SENT' | 'FAILED';

/** A persisted lead, as the store returns it. */
export interface LeadRecord extends ContactInput {
  id: string;
  referenceId: string;
  status: LeadStatus;
  notificationStatus: NotificationStatus;
  notificationAttempts: number;
  /** ISO 8601, generated by the server. Client timestamps are never trusted. */
  submittedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** What the store needs to create a lead — the server-owned fields plus the input. */
export interface NewLead extends ContactInput {
  referenceId: string;
  submittedAt: string;
}

/** The structured API response. Deliberately small and leak-free. */
export type ContactResponse =
  | { success: true; referenceId: string }
  | { success: false; code: ContactErrorCode; message: string };

/**
 * Safe, stable error codes. These are the *only* things the client learns about
 * a failure — never a stack trace, a provider response, or a configuration
 * detail. The localized `message` is chosen from a fixed table keyed by code.
 */
export type ContactErrorCode =
  | 'intake_unconfigured'
  | 'validation_failed'
  | 'invalid_consent'
  | 'unknown_field'
  | 'payload_too_large'
  | 'bad_origin'
  | 'rate_limited'
  | 'duplicate'
  | 'rejected'
  | 'expired'
  | 'persistence_failed'
  | 'server_error';
